language: python
python:
    - 3.4
    - 2.7
    - 3.3
sudo: false
install:
    - pip install . coveralls
script:
    - nosetests --with-coverage --cover-package traitlets traitlets
after_success:
    - coveralls
