language: python
python:
    - 3.5
    - 3.4
    - 2.7
    - 3.3
sudo: false
install:
    - pip install . nose2
    - pip install . cov-core
script:
    - nose2 --with-coverage
after_success:
    - coveralls
